app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, PasswordField
from wtforms.validators import DataRequired, Length, ValidationError, Email, EqualTo, Optional
from app.models import User

class PostForm(FlaskForm):
    post = TextAreaField('Say something', validators=[
        DataRequired(), Length(min=1, max=9999)
    ])
    submit = SubmitField('Submit')
    comment = TextAreaField('Comment', validators=[DataRequired()])
    

class EditProfile(FlaskForm):
    current_password = PasswordField('Current Password', validators=[DataRequired()])
    username = StringField('Username', validators=[DataRequired(), Length(min=1, max=64)])
    email = StringField('Email', validators=[DataRequired(), Email()])
    about_me = TextAreaField('About Me', validators=[Optional(), Length(max=140)])
    password = PasswordField('Password', validators=[Optional(), Length(min=6)])
    new_password = PasswordField('New Password', validators=[Optional(), Length(min=6)])
    submit = SubmitField('Submit')

    def __init__(self, original_username, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.original_username = original_username

    def validate_username(self, username):
        if username.data != self.original_username:
            user = User.query.filter_by(username=username.data).first()
            if user is not None:
                raise ValidationError('Please use a different username.')

class EmptyForm(FlaskForm):
    submit = SubmitField('Submit')

class MessageForm(FlaskForm):
    message = TextAreaField('Message', validators=[
        DataRequired(), Length(min=0, max=140)
    ])
    submit = SubmitField('Submit')

class ResetPasswordRequestForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    submit = SubmitField('Request Password Reset')

class ResetPasswordForm(FlaskForm):
    password = PasswordField('Password', validators=[DataRequired()])
    password2 = PasswordField(
        'Repeat Password', validators=[DataRequired(), EqualTo('password')]
    )
    submit = SubmitField('Request Password Reset')

class CommentForm(FlaskForm):
    comment = TextAreaField('Comment', validators=[
        DataRequired(), Length(min=1, max=140)
    ])
    submit = SubmitField('Submit') 

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes 

app/main/routes.py
from flask import render_template, flash, redirect, url_for, request, current_app, jsonify
from flask_login import current_user, login_required
from app import db
from app.main import bp
from app.models import User, Post, Message, followers as followers_table, Activity
from app.main.forms import PostForm, EditProfile, EmptyForm, MessageForm, ResetPasswordForm, ResetPasswordRequestForm
from datetime import datetime, timezone
from sqlalchemy import or_
from app.email import send_password_reset_email
from app.main.forms import CommentForm
from flask_wtf import FlaskForm
from wtforms import TextAreaField, SubmitField, StringField, PasswordField
from wtforms.validators import DataRequired, Length, Email, Optional
from werkzeug.security import check_password_hash
import requests
from app.services.news_services import get_random_news

@bp.before_app_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.now(timezone.utc)
        db.session.commit()

@bp.route('/', methods=['GET'])
@bp.route('/index', methods=['GET'])
@login_required
def index():
    page = request.args.get('page', 1, type=int)
    posts = db.session.query(Post).join(
        followers_table, (followers_table.c.followed_id == Post.user_id)
    ).filter(followers_table.c.follower_id == current_user.id).order_by(
        Post.timestamp.desc()
    ).paginate(page=page, per_page=current_app.config['POSTS_PER_PAGE'], error_out=False)

    form = PostForm()
    if form.validate_on_submit():
        post = Post(body=form.post.data.strip(), author=current_user)
        db.session.add(post)
        try:
            db.session.commit()
        except Exception as e:
            current_app.logger.error(f'Error committing post: {str(e)}')
            db.session.rollback()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.index'))
    else:
        current_app.logger.debug(f'Form errors: {form.errors}')

    recent_activities = Activity.query.order_by(Activity.timestamp.desc()).limit(10).all()
    return render_template('main/index.html', 
                         title='Home',
                         form=form,
                         posts=posts.items,
                         recent_activities=recent_activities)

@bp.route('/explore', methods=['GET'])
def explore():
    search_query = request.args.get('q', '').strip()
    
    if search_query:
        # Search users
        users = User.query.filter(or_(
            User.username.ilike(f'%{search_query}%'),
            User.about_me.ilike(f'%{search_query}%')
        )).limit(8).all()
        
        # Search posts
        posts = Post.query.filter(or_(
            Post.body.ilike(f'%{search_query}%'),
            Post.author.has(User.username.ilike(f'%{search_query}%'))
        )).order_by(Post.timestamp.desc()).limit(10).all()
        
        return render_template('main/explore.html',
                             title='Search Results',
                             search_query=search_query,
                             users=users,
                             posts=posts)
    
    # If no search query, show regular explore page with sorting and filtering
    page = request.args.get('page', 1, type=int)
    sort = request.args.get('sort', 'recent')
    filter_type = request.args.get('filter', 'all')
    
    posts_query = Post.query
    
    if sort == 'popular':
        posts_query = posts_query.order_by(Post.likes_count.desc())
    elif sort == 'commented':
        posts_query = posts_query.order_by(Post.comments_count.desc())
    else:
        posts_query = posts_query.order_by(Post.timestamp.desc())
    
    featured_users = User.query.order_by(User.followers_count.desc()).limit(4).all()
    
    posts = posts_query.paginate(
        page=page, per_page=current_app.config['POSTS_PER_PAGE'], error_out=False)
    
    latest_news = get_random_news()
    
    return render_template('main/explore.html',
                         title='Explore',
                         posts=posts.items,
                         featured_users=featured_users,
                         search_query=search_query,
                         news=latest_news)

@bp.route('/user/<username>', methods=['GET', 'POST'])
@login_required
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    form = PostForm()
    
    if form.validate_on_submit():
        try:
            post = Post(body=form.post.data.strip(), author=current_user)
            db.session.add(post)
            db.session.commit()
            flash('Your post has been created!', 'success')
            return redirect(url_for('main.user', username=username))
        except Exception as e:
            current_app.logger.error(f'Error committing post: {str(e)}')
            db.session.rollback()
            flash('An error occurred while creating your post. Please try again.', 'danger')
    else:
        flash('Please correct the errors in the form.', 'danger')
        current_app.logger.debug(f'Form errors: {form.errors}')
    
    posts = Post.query.filter_by(author=user).order_by(Post.timestamp.desc()).all()
    current_app.logger.debug(f'Number of posts for user {user.username}: {len(posts)}')
    
    return render_template('main/user.html', user=user, posts=posts, form=form)

@bp.route('/edit_profile/<username>', methods=['GET', 'POST'])
@login_required
def edit_profile(username):
    form = EditProfile(original_username=username)
    if form.validate_on_submit():
        if check_password_hash(current_user.password_hash, form.current_password.data):
            if form.new_password.data:
                current_user.set_password(form.new_password.data)
            current_user.username = form.username.data
            current_user.email = form.email.data
            current_user.about_me = form.about_me.data
            db.session.commit()
            flash('Your changes have been saved.')
            return redirect(url_for('main.profile', username=current_user.username))
        else:
            flash('Current password is incorrect.', 'danger')
    return render_template('main/edit_profile.html', form=form, user=current_user)

@bp.route('/follow/<username>', methods=['POST'])
@login_required
def follow(username):
    form = EmptyForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=username).first()
        if user is None:
            flash(f'User {username} not found.')
            return redirect(url_for('main.index'))
        if user == current_user:
            flash('You cannot follow yourself!')
            return redirect(url_for('main.user', username=username))
        
        try:
            if current_user.follow(user):
                db.session.commit()
                flash(f'You are now following {username}!')
            else:
                flash(f'You are already following {username}.')
        except Exception as e:
            db.session.rollback()  # Rollback the session in case of error
            current_app.logger.error(f'Error following user {username}: {e}')
            flash('An error occurred while trying to follow the user. Please try again.')
        
        return redirect(url_for('main.user', username=username))
    
    flash('There was an issue with your follow request. Please try again.')
    return redirect(url_for('main.explore', q=request.args.get('q', '')))

@bp.route('/unfollow/<username>', methods=['POST'])
@login_required
def unfollow(username):
    form = EmptyForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=username).first()
        if user is None:
            flash(f'User {username} not found.')
            return redirect(url_for('main.index'))
        if user == current_user:
            flash('You cannot unfollow yourself!')
            return redirect(url_for('main.user', username=username))
        current_user.unfollow(user)
        db.session.commit()
        flash(f'You have unfollowed {username}.')
        return redirect(url_for('main.user', username=username))
    return redirect(url_for('main.index'))

# API routes for post interactions
@bp.route('/api/posts/<int:post_id>/like', methods=['POST'])
@login_required
def like_post(post_id):
    post = Post.query.get_or_404(post_id)
    if current_user in post.likes:
        post.likes.remove(current_user)
        post.likes_count -= 1
    else:
        post.likes.append(current_user)
        post.likes_count += 1
    db.session.commit()
    return jsonify({'likes_count': len(post.likes)})

@bp.route('/api/posts/<int:post_id>/bookmark', methods=['POST'])
@login_required
def bookmark_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post in current_user.bookmarks:
        current_user.bookmarks.remove(post)
    else:
        current_user.bookmarks.append(post)
    db.session.commit()
    return jsonify({'status': 'success'})

@bp.route('/user/<username>/followers')
@login_required
def followers(username):
    user = User.query.filter_by(username=username).first_or_404()
    followers = user.followers.all()
    return render_template('main/followers.html', user=user, followers=followers)

@bp.route('/user/<username>/following')
@login_required
def following(username):
    user = User.query.filter_by(username=username).first_or_404()
    following = user.followed.all()
    return render_template('main/following.html', user=user, following=following)

@bp.route('/reset_password_request', methods=['GET', 'POST'])
def reset_password_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = ResetPasswordRequestForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            send_password_reset_email(user)
        flash('Check your email for instructions to reset your password')
        return redirect(url_for('auth.login'))

app/templates/main/edit_profile.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <!-- Profile Edit Card -->
        <div class="col-md-4">
            <div class="card profile-card">
                <div class="card-body text-center">
                    <img src="{{ current_user.avatar(128) }}" class="rounded-circle profile-avatar mb-3" alt="{{ current_user.username }}">
                    <h3 class="card-title">{{ current_user.username }}</h3>
                    
                    <div class="stats-container mb-4">
                        <div class="stat-item">
                            <a href="{{ url_for('main.following', username=current_user.username) }}">
                                <span class="stat-value">{{ user.followed.count() if user.followed is defined else 0 }}</span>
                                <span class="stat-label">Following</span>
                            </a>
                        </div>
                        <div class="stat-item">
                            <a href="{{ url_for('main.followers', username=current_user.username) }}">
                                <span class="stat-value">{{ user.followers.count() if user.followers is defined else 0 }}</span>
                                <span class="stat-label">Followers</span>
                            </a>
                        </div>
                    </div>

                    <a href="{{ url_for('main.user', username=current_user.username) }}" class="btn btn-outline-secondary w-100">Back to Profile</a>
                </div>
            </div>
        </div>

        <!-- Edit Form Section -->
        <div class="col-md-8">
            <div class="card edit-form-card">
                <div class="card-body">
                    <h4 class="card-title mb-4">Edit Profile</h4>
                    <form action="" method="post">
                        {{ form.hidden_tag() }}
                        
                        <div class="form-group mb-3">
                            {{ form.username.label(class="form-label") }}
                            {{ form.username(class="form-control") }}
                            {% for error in form.username.errors %}
                                <span class="text-danger small">{{ error }}</span>
                            {% endfor %}
                        </div>

                        <div class="form-group mb-3">
                            <label class="form-label">Current Email: {{ current_user.email }}</label>
                            {{ form.email.label(class="form-label") }}
                            {{ form.email(class="form-control") }}
                            {% for error in form.email.errors %}
                                <span class="text-danger small">{{ error }}</span>
                            {% endfor %}
                        </div>

                        <div class="form-group mb-3">
                            {{ form.about_me.label(class="form-label") }}
                            {{ form.about_me(class="form-control", rows=4) }}
                            {% for error in form.about_me.errors %}
                                <span class="text-danger small">{{ error }}</span>
                            {% endfor %}
                        </div>

                        <div class="form-group mb-3">
                            {{ form.current_password.label(class="form-label") }}
                            {{ form.current_password(class="form-control", placeholder="Current password") }}
                            {% for error in form.current_password.errors %}
                                <span class="text-danger small">{{ error }}</span>
                            {% endfor %}
                        </div>

                        <div class="form-group mb-3">
                            {{ form.new_password.label(class="form-label") }}
                            {{ form.new_password(class="form-control", placeholder="Leave blank to keep current password") }}
                            {% for error in form.new_password.errors %}
                                <span class="text-danger small">{{ error }}</span>
                            {% endfor %}
                        </div>

                        <button type="submit" class="btn btn-primary">Save Changes</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<link href="{{ url_for('static', filename='css/user.css') }}" rel="stylesheet">
{% endblock %}

app/templates/main/followers.html
{% extends "base.html" %}

{% block content %}
    <div class="max-w-2xl mx-auto px-4 py-8">
        <div class="mb-8">
            <h1 class="text-2xl font-bold mb-2">Followers of {{ user.username }}</h1>
            <p class="text-gray-600">{{ followers|length }} follower{{ 's' if followers|length != 1 }}</p>
        </div>
        
        <div class="space-y-4">
            {% for follower in followers %}
                <div class="flex items-center justify-between p-4 bg-white rounded-xl shadow-sm">
                    <div class="flex items-center space-x-4">
                        <img src="{{ follower.avatar(64) }}" 
                             alt="{{ follower.username }}'s avatar"
                             class="w-12 h-12 rounded-full">
                        <div>
                            <a href="{{ url_for('main.user', username=follower.username) }}" 
                               class="font-medium hover:text-primary">
                                {{ follower.username }}
                            </a>
                            {% if follower.about_me %}
                                <p class="text-sm text-gray-600">{{ follower.about_me }}</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %} 

app/templates/main/following.html
{% extends "base.html" %}

{% block content %}
    <div class="max-w-2xl mx-auto px-4 py-8">
        <div class="mb-8">
            <h1 class="text-2xl font-bold mb-2">{{ user.username }} is following</h1>
            <p class="text-gray-600">{{ following|length }} following</p>
        </div>
        
        <div class="space-y-4">
            {% for followed in following %}
                <div class="flex items-center justify-between p-4 bg-white rounded-xl shadow-sm">
                    <div class="flex items-center space-x-4">
                        <img src="{{ followed.avatar(64) }}" 
                             alt="{{ followed.username }}'s avatar"
                             class="w-12 h-12 rounded-full">
                        <div>
                            <a href="{{ url_for('main.user', username=followed.username) }}" 
                               class="font-medium hover:text-primary">
                                {{ followed.username }}
                            </a>
                            {% if followed.about_me %}
                                <p class="text-sm text-gray-600">{{ followed.about_me }}</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %} 

app/templates/main/reset_password.html
{% extends "base.html" %}

{% block styles %}
<style>
    .fade-in {
        animation: fadeIn 0.6s ease-in;
    }
    
    @keyframes fadeIn {
        0% {
            opacity: 0;
            transform: translateY(10px);
        }
        100% {
            opacity: 1;
            transform: translateY(0);
        }
    }

    .social-btn:hover {
        transform: translateY(-2px);
        transition: all 0.3s ease;
    }

    .divider::before,
    .divider::after {
        content: "";
        flex: 1;
        border-bottom: 1px solid #e5e7eb;
    }
</style>
{% endblock %}

{% block content %}
<section class="min-h-screen bg-[#F4F7FF] lg:py-20 md:py-16 py-12"></section>
    <div class="container mx-auto px-4">
        <div class="max-w-[525px] mx-auto">
            <!-- Main Card -->
            <div class="fade-in bg-white rounded-xl relative overflow-hidden 
                        py-12 px-6 sm:px-8 md:px-12 
                        shadow-[0_4px_20px_rgba(0,0,0,0.05)]">

                <!-- Form -->
                <form class="space-y-6" action="" method="post">
                    {{ form.hidden_tag() }}
                    <h1 class="text-gray-900 font-bold text-xl sm:text-2xl md:text-3xl mb-3"></h1>
                        Sign in to your account
                    </h1>
                    <div class="space-y-2">
                        {{ form.username.label(class="text-sm md:text-base font-medium text-gray-900 block") }}
                        {{ form.username(class="w-full rounded-lg border border-gray-300 
                                             py-2.5 md:py-3 px-4 
                                             text-sm md:text-base font-medium text-gray-900 
                                             outline-none transition 
                                             focus:border-gray-600 focus:shadow-md", 
                                             placeholder="Enter your username") }}
                        {% for error in form.username.errors %}
                        <p class="text-red-500 text-xs md:text-sm mt-1">{{ error }}</p>
                        {% endfor %}
                    </div>
                    
                    <div class="space-y-2">
                        {{ form.password.label(class="text-sm md:text-base font-medium text-gray-900 block") }}
                        {{ form.password(class="w-full rounded-lg border border-gray-300 
                                             py-2.5 md:py-3 px-4 
                                             text-sm md:text-base font-medium text-gray-900 
                                             outline-none transition 
                                             focus:border-gray-600 focus:shadow-md", 
                                             placeholder="Enter your password") }}
                        {% for error in form.password.errors %}
                        <p class="text-red-500 text-xs md:text-sm mt-1">{{ error }}</p>
                        {% endfor %}
                    </div>

                    <!-- Submit Button -->
                    <button type="submit" 
                            class="w-full px-6 py-2.5 md:py-3 
                                   text-sm md:text-base font-medium text-white 
                                   bg-gray-900 rounded-lg 
                                   hover:bg-gray-800 transition duration-200 hover:shadow-md">
                        Sign in
                    </button>

                    <!-- Sign Up Link -->
                    <p class="text-sm md:text-base text-gray-600 text-center mt-6">
                        OR
                        <a href="{{ url_for('auth.register') }}" 
                           class="text-gray-900 hover:underline font-medium">
                            Create New Account!
                        </a>
                    </p>
                </form>
            </div>
        </div>
    </div>
</section>
    <!-- <h1>Reset Your Password</h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}<br>
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password2.label }}<br>
            {{ form.password2(size=32) }}<br>
            {% for error in form.password2.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}  -->

app/templates/main/user.html
{% extends "base.html" %}

{% block content %}
<!-- Profile Header Section -->
<section class="bg-gradient-to-b from-gray-50 to-white min-h-screen">
    <div class="container max-w-7xl mx-auto px-4 py-16">
        <!-- Two Column Layout -->
        <div class="flex flex-col lg:flex-row gap-12">
            <!-- Profile Column -->
            <div class="lg:w-1/3 space-y-8">
                <!-- Main Profile Card -->
                <div class="bg-white rounded-2xl border border-gray-100 shadow-lg overflow-hidden">
                    <!-- Cover Photo Area -->
                    <div class="h-32 bg-gradient-to-r from-primary/20 to-primary/10"></div>
                    
                    <!-- Profile Info -->
                    <div class="px-8 pb-8 -mt-16">
                        <!-- Avatar -->
                        <div class="relative mb-6">
                            <div class="absolute inset-0 bg-primary/5 rounded-full scale-110"></div>
                            <img src="{{ user.avatar(192) }}" 
                                 class="relative w-32 h-32 rounded-full border-4 border-white shadow-xl mx-auto" 
                                 alt="{{ user.username }}">
                        </div>

                        <!-- User Info -->
                        <div class="text-center mb-8">
                            <h1 class="text-2xl font-bold text-gray-900 mb-2">{{ user.username }}</h1>
                            <a href="{{ url_for('main.edit_profile', username=user.username) }}" class="text-gray-500 hover:text-gray-800 transition-all duration-300">
                                <i class="fas fa-pencil-alt"></i> Edit Profile
                            </a>
                            {% if user.about_me %}
                                <p class="text-gray-600">{{ user.about_me }}</p>
                            {% endif %}
                        </div>

                        <!-- Stats Cards -->
                        <div class="grid grid-cols-2 gap-4 mb-8">
                            <div class="bg-gray-50 rounded-xl p-4 text-center">
                                <a href="{{ url_for('main.following', username=user.username) }}" class="block">
                                    <span class="block text-2xl font-bold text-primary">
                                        {{ user.followed.count() if user.followed is defined else 0 }}
                                    </span>
                                    <span class="text-sm text-gray-600">Following</span>
                                </a>
                            </div>
                            <div class="bg-gray-50 rounded-xl p-4 text-center">
                                <a href="{{ url_for('main.followers', username=user.username) }}" class="block">
                                    <span class="block text-2xl font-bold text-primary">
                                        {{ user.followers.count() if user.followers is defined else 0 }}
                                    </span>
                                    <span class="text-sm text-gray-600">Followers</span>
                                </a>
                            </div>
                        </div>

                

                        <!-- Action Buttons -->
                        {% if user != current_user %}
                            <div class="space-y-3">
                                {% if not current_user.is_following(user) %}
                                <form action="{{ url_for('main.follow', username=user.username) }}" method="post">
                                    {{ form.hidden_tag() }}
                                    <button type="submit" 
                                            class="w-full px-6 py-3 rounded-xl bg-primary text-black font-medium
                                                   hover:bg-primary-dark transition-all duration-300 shadow-md hover:shadow-lg">
                                        Follow
                                    </button>
                                </form>
                                {% else %}
                                <form action="{{ url_for('main.unfollow', username=user.username) }}" method="post">
                                    {{ form.hidden_tag() }}
                                    <button type="submit" 
                                            class="w-full px-6 py-3 rounded-xl border-2 border-primary text-primary font-medium
                                                   hover:bg-primary hover:text-black transition-all duration-300">
                                        Unfollow
                                    </button>
                                </form>
                                {% endif %}
                                <a href="{{ url_for('main.send_message', recipient=user.username) }}"
                                   class="block w-full px-6 py-3 rounded-xl bg-gray-50 text-gray-700 font-medium text-center
                                          hover:bg-gray-100 transition-all duration-300">
                                    Send Message
                                </a>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>

            <!-- Posts Column -->
            <div class="lg:w-2/3 space-y-8">
                {% if user == current_user %}
                    <div class="bg-white rounded-2xl border border-gray-100 shadow-lg p-6">
                        {% include '_post_form.html' %}
                    </div>
                {% endif %}

                <!-- Posts List -->
                <div class="bg-white rounded-2xl border border-gray-100 shadow-lg overflow-hidden">
                    <div class="px-6 py-4 border-b border-gray-100 flex items-center justify-between">
                        <h2 class="text-xl font-bold text-gray-900">Posts</h2>
                        <span class="text-sm text-gray-500">{{ posts|length }} posts</span>
                    </div>
                    
                    {% if posts %}
                        <div class="divide-y divide-gray-100">
                            {% for post in posts %}
                                <div class="p-6 hover:bg-gray-50 transition-all duration-300">
                                    {% include '_post.html' %}
                                </div>
                            {% endfor %}
                        </div>
                    {% else %}
                        <div class="p-12 text-center text-gray-500">
                            <i class="fas fa-pencil-alt text-4xl mb-4"></i>
                            <p>No posts yet</p>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block styles %}
<link href="{{ url_for('static', filename='css/user.css') }}" rel="stylesheet">
{% endblock %}